name = "electric cowboy"
author = "sylvrs"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28b25cc2924216e7624f38231c1c84a647205881ae38220bcad66b49d2e24b75"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
