name = "electric cowboy"
author = "sylvrs"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7957b06f4f2d8c825c38268ebd3ec3aac96911aa90ee9e943600baab012e4ed"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
