name = "electric cowboy"
author = "sylvrs"
version = "1.2.0-alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05fee3bb4fd2c370fb845bfa3e905be8085cc7f60875cf2aa0860935bf78955b"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
