name = "electric cowboy"
author = "sylvrs"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1009e36573c83edc8d149b6130fd70e5f4589ad4778917fe6a916f26383e7b4d"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
